"""
Módulo para gerenciar a API de alimentos
Em produção, você pode integrar com APIs reais como FatSecret, USDA, etc.
"""

import requests
from typing import List, Dict, Any

class FoodAPIService:
    """Serviço para buscar alimentos em APIs externas"""
    
    def __init__(self):
        # Em produção, você precisaria de chaves de API reais
        self.fatsecret_api_key = None  # Configure sua chave aqui
        self.usda_api_key = None  # Configure sua chave aqui
        
    def search_fatsecret(self, query: str) -> List[Dict[str, Any]]:
        """
        Busca alimentos na API do FatSecret
        Em produção, você precisaria de uma chave de API válida
        """
        # Simulação da API do FatSecret com muito mais alimentos
        sample_foods = [
            # Cereais e Grãos
            {
                'name': 'Arroz Branco Cozido',
                'brand': 'Genérico',
                'calories': 130,
                'protein': 2.7,
                'carbohydrates': 28.2,
                'fat': 0.3,
                'fiber': 0.4,
                'sugar': 0.1,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Arroz Integral Cozido',
                'brand': 'Genérico',
                'calories': 111,
                'protein': 2.6,
                'carbohydrates': 23.0,
                'fat': 0.9,
                'fiber': 1.8,
                'sugar': 0.4,
                'sodium': 5,
                'serving_size': '100g'
            },
            {
                'name': 'Aveia',
                'brand': 'Genérico',
                'calories': 389,
                'protein': 16.9,
                'carbohydrates': 66.3,
                'fat': 6.9,
                'fiber': 10.6,
                'sugar': 0.0,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Pão Integral',
                'brand': 'Genérico',
                'calories': 247,
                'protein': 13.0,
                'carbohydrates': 41.0,
                'fat': 4.2,
                'fiber': 7.0,
                'sugar': 6.0,
                'sodium': 400,
                'serving_size': '100g'
            },
            {
                'name': 'Pão Branco',
                'brand': 'Genérico',
                'calories': 265,
                'protein': 9.0,
                'carbohydrates': 49.0,
                'fat': 3.2,
                'fiber': 2.7,
                'sugar': 5.0,
                'sodium': 490,
                'serving_size': '100g'
            },
            {
                'name': 'Quinoa Cozida',
                'brand': 'Genérico',
                'calories': 120,
                'protein': 4.4,
                'carbohydrates': 21.3,
                'fat': 1.9,
                'fiber': 2.8,
                'sugar': 0.9,
                'sodium': 7,
                'serving_size': '100g'
            },
            {
                'name': 'Arroz Basmati',
                'brand': 'Genérico',
                'calories': 121,
                'protein': 2.7,
                'carbohydrates': 25.2,
                'fat': 0.4,
                'fiber': 0.6,
                'sugar': 0.1,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Arroz Arbóreo',
                'brand': 'Genérico',
                'calories': 130,
                'protein': 2.7,
                'carbohydrates': 28.2,
                'fat': 0.3,
                'fiber': 0.4,
                'sugar': 0.1,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Granola',
                'brand': 'Genérico',
                'calories': 471,
                'protein': 10.0,
                'carbohydrates': 64.0,
                'fat': 20.0,
                'fiber': 8.0,
                'sugar': 24.0,
                'sodium': 49,
                'serving_size': '100g'
            },
            {
                'name': 'Muesli',
                'brand': 'Genérico',
                'calories': 340,
                'protein': 8.0,
                'carbohydrates': 66.0,
                'fat': 6.0,
                'fiber': 7.0,
                'sugar': 26.0,
                'sodium': 49,
                'serving_size': '100g'
            },
            {
                'name': 'Pão de Centeio',
                'brand': 'Genérico',
                'calories': 259,
                'protein': 8.5,
                'carbohydrates': 48.0,
                'fat': 3.3,
                'fiber': 6.0,
                'sugar': 4.0,
                'sodium': 603,
                'serving_size': '100g'
            },
            {
                'name': 'Pão de Aveia',
                'brand': 'Genérico',
                'calories': 269,
                'protein': 10.0,
                'carbohydrates': 44.0,
                'fat': 4.4,
                'fiber': 4.0,
                'sugar': 6.0,
                'sodium': 400,
                'serving_size': '100g'
            },
            {
                'name': 'Tapioca',
                'brand': 'Genérico',
                'calories': 360,
                'protein': 0.2,
                'carbohydrates': 88.0,
                'fat': 0.0,
                'fiber': 0.9,
                'sugar': 0.0,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Farinha de Trigo',
                'brand': 'Genérico',
                'calories': 364,
                'protein': 10.0,
                'carbohydrates': 76.0,
                'fat': 1.0,
                'fiber': 2.7,
                'sugar': 0.3,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Farinha de Mandioca',
                'brand': 'Genérico',
                'calories': 360,
                'protein': 1.4,
                'carbohydrates': 87.0,
                'fat': 0.3,
                'fiber': 1.8,
                'sugar': 3.4,
                'sodium': 1,
                'serving_size': '100g'
            },
            
            # Proteínas
            {
                'name': 'Frango Grelhado',
                'brand': 'Genérico',
                'calories': 165,
                'protein': 31.0,
                'carbohydrates': 0.0,
                'fat': 3.6,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 74,
                'serving_size': '100g'
            },
            {
                'name': 'Peito de Frango',
                'brand': 'Genérico',
                'calories': 165,
                'protein': 31.0,
                'carbohydrates': 0.0,
                'fat': 3.6,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 74,
                'serving_size': '100g'
            },
            {
                'name': 'Atum Enlatado',
                'brand': 'Genérico',
                'calories': 184,
                'protein': 26.5,
                'carbohydrates': 0.0,
                'fat': 8.1,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 396,
                'serving_size': '100g'
            },
            {
                'name': 'Salmão Grelhado',
                'brand': 'Genérico',
                'calories': 208,
                'protein': 25.0,
                'carbohydrates': 0.0,
                'fat': 12.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 59,
                'serving_size': '100g'
            },
            {
                'name': 'Ovo Cozido',
                'brand': 'Genérico',
                'calories': 155,
                'protein': 12.6,
                'carbohydrates': 1.1,
                'fat': 11.3,
                'fiber': 0.0,
                'sugar': 1.1,
                'sodium': 124,
                'serving_size': '100g'
            },
            {
                'name': 'Carne Bovina Grelhada',
                'brand': 'Genérico',
                'calories': 250,
                'protein': 26.0,
                'carbohydrates': 0.0,
                'fat': 15.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 72,
                'serving_size': '100g'
            },
            {
                'name': 'Porco Grelhado',
                'brand': 'Genérico',
                'calories': 242,
                'protein': 27.0,
                'carbohydrates': 0.0,
                'fat': 14.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 62,
                'serving_size': '100g'
            },
            {
                'name': 'Salmão Enlatado',
                'brand': 'Genérico',
                'calories': 208,
                'protein': 25.0,
                'carbohydrates': 0.0,
                'fat': 12.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 59,
                'serving_size': '100g'
            },
            {
                'name': 'Atum Fresco',
                'brand': 'Genérico',
                'calories': 144,
                'protein': 23.4,
                'carbohydrates': 0.0,
                'fat': 4.9,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 39,
                'serving_size': '100g'
            },
            {
                'name': 'Sardinha Enlatada',
                'brand': 'Genérico',
                'calories': 208,
                'protein': 24.6,
                'carbohydrates': 0.0,
                'fat': 11.5,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 505,
                'serving_size': '100g'
            },
            {
                'name': 'Bacalhau',
                'brand': 'Genérico',
                'calories': 105,
                'protein': 23.0,
                'carbohydrates': 0.0,
                'fat': 0.9,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 78,
                'serving_size': '100g'
            },
            {
                'name': 'Tilápia',
                'brand': 'Genérico',
                'calories': 96,
                'protein': 20.1,
                'carbohydrates': 0.0,
                'fat': 2.3,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 52,
                'serving_size': '100g'
            },
            {
                'name': 'Camarão',
                'brand': 'Genérico',
                'calories': 99,
                'protein': 24.0,
                'carbohydrates': 0.2,
                'fat': 0.3,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 111,
                'serving_size': '100g'
            },
            {
                'name': 'Lula',
                'brand': 'Genérico',
                'calories': 92,
                'protein': 15.6,
                'carbohydrates': 2.0,
                'fat': 1.4,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 44,
                'serving_size': '100g'
            },
            {
                'name': 'Carne de Cordeiro',
                'brand': 'Genérico',
                'calories': 294,
                'protein': 25.6,
                'carbohydrates': 0.0,
                'fat': 21.2,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 72,
                'serving_size': '100g'
            },
            {
                'name': 'Carne de Vitela',
                'brand': 'Genérico',
                'calories': 143,
                'protein': 20.1,
                'carbohydrates': 0.0,
                'fat': 7.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 72,
                'serving_size': '100g'
            },
            {
                'name': 'Peru',
                'brand': 'Genérico',
                'calories': 189,
                'protein': 29.0,
                'carbohydrates': 0.0,
                'fat': 7.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 70,
                'serving_size': '100g'
            },
            {
                'name': 'Pato',
                'brand': 'Genérico',
                'calories': 337,
                'protein': 19.0,
                'carbohydrates': 0.0,
                'fat': 28.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 65,
                'serving_size': '100g'
            },
            
            # Laticínios
            {
                'name': 'Leite Integral',
                'brand': 'Genérico',
                'calories': 61,
                'protein': 3.2,
                'carbohydrates': 4.8,
                'fat': 3.3,
                'fiber': 0.0,
                'sugar': 4.8,
                'sodium': 43,
                'serving_size': '100ml'
            },
            {
                'name': 'Leite Desnatado',
                'brand': 'Genérico',
                'calories': 42,
                'protein': 3.4,
                'carbohydrates': 5.0,
                'fat': 0.1,
                'fiber': 0.0,
                'sugar': 5.0,
                'sodium': 44,
                'serving_size': '100ml'
            },
            {
                'name': 'Iogurte Natural',
                'brand': 'Genérico',
                'calories': 59,
                'protein': 10.0,
                'carbohydrates': 3.6,
                'fat': 0.4,
                'fiber': 0.0,
                'sugar': 3.2,
                'sodium': 36,
                'serving_size': '100g'
            },
            {
                'name': 'Iogurte Grego',
                'brand': 'Genérico',
                'calories': 133,
                'protein': 23.0,
                'carbohydrates': 3.6,
                'fat': 0.4,
                'fiber': 0.0,
                'sugar': 3.2,
                'sodium': 36,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Cottage',
                'brand': 'Genérico',
                'calories': 98,
                'protein': 11.0,
                'carbohydrates': 3.4,
                'fat': 4.3,
                'fiber': 0.0,
                'sugar': 2.7,
                'sodium': 364,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Ricotta',
                'brand': 'Genérico',
                'calories': 174,
                'protein': 11.0,
                'carbohydrates': 3.0,
                'fat': 13.0,
                'fiber': 0.0,
                'sugar': 0.3,
                'sodium': 84,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Minas',
                'brand': 'Genérico',
                'calories': 253,
                'protein': 21.0,
                'carbohydrates': 2.0,
                'fat': 18.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 336,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Prato',
                'brand': 'Genérico',
                'calories': 364,
                'protein': 25.0,
                'carbohydrates': 2.0,
                'fat': 30.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 700,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Mussarela',
                'brand': 'Genérico',
                'calories': 280,
                'protein': 28.0,
                'carbohydrates': 2.0,
                'fat': 17.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 627,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Parmesão',
                'brand': 'Genérico',
                'calories': 431,
                'protein': 38.0,
                'carbohydrates': 4.0,
                'fat': 29.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 1529,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Gorgonzola',
                'brand': 'Genérico',
                'calories': 353,
                'protein': 21.0,
                'carbohydrates': 2.0,
                'fat': 28.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 1400,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Brie',
                'brand': 'Genérico',
                'calories': 334,
                'protein': 21.0,
                'carbohydrates': 0.5,
                'fat': 28.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 629,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Cheddar',
                'brand': 'Genérico',
                'calories': 403,
                'protein': 25.0,
                'carbohydrates': 1.3,
                'fat': 33.0,
                'fiber': 0.0,
                'sugar': 0.5,
                'sodium': 621,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Provolone',
                'brand': 'Genérico',
                'calories': 351,
                'protein': 25.6,
                'carbohydrates': 2.1,
                'fat': 27.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 876,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Feta',
                'brand': 'Genérico',
                'calories': 264,
                'protein': 14.2,
                'carbohydrates': 4.1,
                'fat': 21.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 917,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Coalho',
                'brand': 'Genérico',
                'calories': 321,
                'protein': 22.0,
                'carbohydrates': 2.0,
                'fat': 25.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 700,
                'serving_size': '100g'
            },
            {
                'name': 'Manteiga',
                'brand': 'Genérico',
                'calories': 717,
                'protein': 0.9,
                'carbohydrates': 0.1,
                'fat': 81.0,
                'fiber': 0.0,
                'sugar': 0.1,
                'sodium': 11,
                'serving_size': '100g'
            },
            {
                'name': 'Margarina',
                'brand': 'Genérico',
                'calories': 717,
                'protein': 0.2,
                'carbohydrates': 0.0,
                'fat': 81.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Creme de Leite',
                'brand': 'Genérico',
                'calories': 340,
                'protein': 2.0,
                'carbohydrates': 3.0,
                'fat': 37.0,
                'fiber': 0.0,
                'sugar': 3.0,
                'sodium': 40,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Cottage',
                'brand': 'Genérico',
                'calories': 98,
                'protein': 11.0,
                'carbohydrates': 3.4,
                'fat': 4.3,
                'fiber': 0.0,
                'sugar': 2.7,
                'sodium': 364,
                'serving_size': '100g'
            },
            {
                'name': 'Queijo Minas',
                'brand': 'Genérico',
                'calories': 253,
                'protein': 21.0,
                'carbohydrates': 2.0,
                'fat': 18.0,
                'fiber': 0.0,
                'sugar': 1.0,
                'sodium': 620,
                'serving_size': '100g'
            },
            
            # Frutas
            {
                'name': 'Banana',
                'brand': 'Genérico',
                'calories': 89,
                'protein': 1.1,
                'carbohydrates': 22.8,
                'fat': 0.3,
                'fiber': 2.6,
                'sugar': 12.2,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Maçã',
                'brand': 'Genérico',
                'calories': 52,
                'protein': 0.3,
                'carbohydrates': 14.0,
                'fat': 0.2,
                'fiber': 2.4,
                'sugar': 10.4,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Laranja',
                'brand': 'Genérico',
                'calories': 47,
                'protein': 0.9,
                'carbohydrates': 11.8,
                'fat': 0.1,
                'fiber': 2.4,
                'sugar': 9.4,
                'sodium': 0,
                'serving_size': '100g'
            },
            {
                'name': 'Morango',
                'brand': 'Genérico',
                'calories': 32,
                'protein': 0.7,
                'carbohydrates': 7.7,
                'fat': 0.3,
                'fiber': 2.0,
                'sugar': 4.9,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Uva',
                'brand': 'Genérico',
                'calories': 62,
                'protein': 0.6,
                'carbohydrates': 16.0,
                'fat': 0.2,
                'fiber': 0.9,
                'sugar': 16.0,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Abacaxi',
                'brand': 'Genérico',
                'calories': 50,
                'protein': 0.5,
                'carbohydrates': 13.1,
                'fat': 0.1,
                'fiber': 1.4,
                'sugar': 9.9,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Manga',
                'brand': 'Genérico',
                'calories': 60,
                'protein': 0.8,
                'carbohydrates': 15.0,
                'fat': 0.4,
                'fiber': 1.6,
                'sugar': 13.7,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Pêssego',
                'brand': 'Genérico',
                'calories': 39,
                'protein': 0.9,
                'carbohydrates': 9.5,
                'fat': 0.3,
                'fiber': 1.5,
                'sugar': 8.4,
                'sodium': 0,
                'serving_size': '100g'
            },
            {
                'name': 'Pera',
                'brand': 'Genérico',
                'calories': 57,
                'protein': 0.4,
                'carbohydrates': 15.2,
                'fat': 0.1,
                'fiber': 3.1,
                'sugar': 9.8,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Kiwi',
                'brand': 'Genérico',
                'calories': 61,
                'protein': 1.1,
                'carbohydrates': 14.7,
                'fat': 0.5,
                'fiber': 3.0,
                'sugar': 9.0,
                'sodium': 3,
                'serving_size': '100g'
            },
            {
                'name': 'Abacate',
                'brand': 'Genérico',
                'calories': 160,
                'protein': 2.0,
                'carbohydrates': 8.5,
                'fat': 14.7,
                'fiber': 6.7,
                'sugar': 0.7,
                'sodium': 7,
                'serving_size': '100g'
            },
            {
                'name': 'Limão',
                'brand': 'Genérico',
                'calories': 29,
                'protein': 1.1,
                'carbohydrates': 9.3,
                'fat': 0.3,
                'fiber': 2.8,
                'sugar': 1.5,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Lima',
                'brand': 'Genérico',
                'calories': 30,
                'protein': 0.7,
                'carbohydrates': 10.5,
                'fat': 0.2,
                'fiber': 2.8,
                'sugar': 1.7,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Tangerina',
                'brand': 'Genérico',
                'calories': 53,
                'protein': 0.8,
                'carbohydrates': 13.3,
                'fat': 0.3,
                'fiber': 1.8,
                'sugar': 10.6,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Ameixa',
                'brand': 'Genérico',
                'calories': 46,
                'protein': 0.7,
                'carbohydrates': 11.4,
                'fat': 0.3,
                'fiber': 1.4,
                'sugar': 9.9,
                'sodium': 0,
                'serving_size': '100g'
            },
            {
                'name': 'Cereja',
                'brand': 'Genérico',
                'calories': 50,
                'protein': 1.0,
                'carbohydrates': 12.2,
                'fat': 0.3,
                'fiber': 1.6,
                'sugar': 8.5,
                'sodium': 0,
                'serving_size': '100g'
            },
            {
                'name': 'Framboesa',
                'brand': 'Genérico',
                'calories': 52,
                'protein': 1.2,
                'carbohydrates': 11.9,
                'fat': 0.7,
                'fiber': 6.5,
                'sugar': 4.4,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Amora',
                'brand': 'Genérico',
                'calories': 43,
                'protein': 1.4,
                'carbohydrates': 9.6,
                'fat': 0.5,
                'fiber': 5.3,
                'sugar': 4.9,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Mirtilo',
                'brand': 'Genérico',
                'calories': 57,
                'protein': 0.7,
                'carbohydrates': 14.5,
                'fat': 0.3,
                'fiber': 2.4,
                'sugar': 10.0,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Coco',
                'brand': 'Genérico',
                'calories': 354,
                'protein': 3.3,
                'carbohydrates': 15.2,
                'fat': 33.5,
                'fiber': 9.0,
                'sugar': 6.2,
                'sodium': 20,
                'serving_size': '100g'
            },
            {
                'name': 'Coco Ralado',
                'brand': 'Genérico',
                'calories': 660,
                'protein': 6.6,
                'carbohydrates': 23.7,
                'fat': 64.5,
                'fiber': 16.3,
                'sugar': 7.4,
                'sodium': 37,
                'serving_size': '100g'
            },
            {
                'name': 'Maracujá',
                'brand': 'Genérico',
                'calories': 97,
                'protein': 2.2,
                'carbohydrates': 23.4,
                'fat': 0.7,
                'fiber': 10.4,
                'sugar': 11.2,
                'sodium': 28,
                'serving_size': '100g'
            },
            {
                'name': 'Goiaba',
                'brand': 'Genérico',
                'calories': 68,
                'protein': 2.6,
                'carbohydrates': 14.3,
                'fat': 0.9,
                'fiber': 5.4,
                'sugar': 9.0,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Caqui',
                'brand': 'Genérico',
                'calories': 70,
                'protein': 0.6,
                'carbohydrates': 18.6,
                'fat': 0.2,
                'fiber': 3.6,
                'sugar': 12.5,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Figo',
                'brand': 'Genérico',
                'calories': 74,
                'protein': 0.8,
                'carbohydrates': 19.2,
                'fat': 0.3,
                'fiber': 2.9,
                'sugar': 16.3,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Romã',
                'brand': 'Genérico',
                'calories': 83,
                'protein': 1.7,
                'carbohydrates': 18.7,
                'fat': 1.2,
                'fiber': 4.0,
                'sugar': 13.7,
                'sodium': 3,
                'serving_size': '100g'
            },
            
            # Legumes
            {
                'name': 'Batata Cozida',
                'brand': 'Genérico',
                'calories': 77,
                'protein': 2.0,
                'carbohydrates': 17.0,
                'fat': 0.1,
                'fiber': 2.2,
                'sugar': 0.8,
                'sodium': 5,
                'serving_size': '100g'
            },
            {
                'name': 'Cenoura',
                'brand': 'Genérico',
                'calories': 41,
                'protein': 0.9,
                'carbohydrates': 9.6,
                'fat': 0.2,
                'fiber': 2.8,
                'sugar': 4.7,
                'sodium': 69,
                'serving_size': '100g'
            },
            {
                'name': 'Brócolis',
                'brand': 'Genérico',
                'calories': 34,
                'protein': 2.8,
                'carbohydrates': 7.0,
                'fat': 0.4,
                'fiber': 2.6,
                'sugar': 1.5,
                'sodium': 33,
                'serving_size': '100g'
            },
            {
                'name': 'Espinafre',
                'brand': 'Genérico',
                'calories': 23,
                'protein': 2.9,
                'carbohydrates': 3.6,
                'fat': 0.4,
                'fiber': 2.2,
                'sugar': 0.4,
                'sodium': 79,
                'serving_size': '100g'
            },
            {
                'name': 'Tomate',
                'brand': 'Genérico',
                'calories': 18,
                'protein': 0.9,
                'carbohydrates': 3.9,
                'fat': 0.2,
                'fiber': 1.2,
                'sugar': 2.6,
                'sodium': 5,
                'serving_size': '100g'
            },
            {
                'name': 'Alface',
                'brand': 'Genérico',
                'calories': 15,
                'protein': 1.4,
                'carbohydrates': 2.9,
                'fat': 0.1,
                'fiber': 1.3,
                'sugar': 0.8,
                'sodium': 28,
                'serving_size': '100g'
            },
            {
                'name': 'Batata Doce',
                'brand': 'Genérico',
                'calories': 86,
                'protein': 1.6,
                'carbohydrates': 20.1,
                'fat': 0.1,
                'fiber': 3.0,
                'sugar': 4.2,
                'sodium': 55,
                'serving_size': '100g'
            },
            {
                'name': 'Mandioca',
                'brand': 'Genérico',
                'calories': 160,
                'protein': 1.4,
                'carbohydrates': 38.0,
                'fat': 0.3,
                'fiber': 1.8,
                'sugar': 1.7,
                'sodium': 14,
                'serving_size': '100g'
            },
            {
                'name': 'Inhame',
                'brand': 'Genérico',
                'calories': 118,
                'protein': 1.5,
                'carbohydrates': 27.9,
                'fat': 0.2,
                'fiber': 4.1,
                'sugar': 0.5,
                'sodium': 9,
                'serving_size': '100g'
            },
            {
                'name': 'Abóbora',
                'brand': 'Genérico',
                'calories': 26,
                'protein': 1.0,
                'carbohydrates': 6.5,
                'fat': 0.1,
                'fiber': 0.5,
                'sugar': 2.8,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Chuchu',
                'brand': 'Genérico',
                'calories': 16,
                'protein': 0.8,
                'carbohydrates': 3.9,
                'fat': 0.1,
                'fiber': 1.7,
                'sugar': 1.7,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Berinjela',
                'brand': 'Genérico',
                'calories': 25,
                'protein': 1.0,
                'carbohydrates': 6.0,
                'fat': 0.2,
                'fiber': 3.0,
                'sugar': 3.5,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Abobrinha',
                'brand': 'Genérico',
                'calories': 17,
                'protein': 1.2,
                'carbohydrates': 3.1,
                'fat': 0.3,
                'fiber': 1.0,
                'sugar': 2.5,
                'sodium': 8,
                'serving_size': '100g'
            },
            {
                'name': 'Pepino',
                'brand': 'Genérico',
                'calories': 16,
                'protein': 0.7,
                'carbohydrates': 3.6,
                'fat': 0.1,
                'fiber': 0.5,
                'sugar': 1.7,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Pimentão',
                'brand': 'Genérico',
                'calories': 20,
                'protein': 0.9,
                'carbohydrates': 4.6,
                'fat': 0.2,
                'fiber': 1.7,
                'sugar': 2.4,
                'sodium': 4,
                'serving_size': '100g'
            },
            {
                'name': 'Cebola',
                'brand': 'Genérico',
                'calories': 40,
                'protein': 1.1,
                'carbohydrates': 9.3,
                'fat': 0.1,
                'fiber': 1.7,
                'sugar': 4.7,
                'sodium': 4,
                'serving_size': '100g'
            },
            {
                'name': 'Alho',
                'brand': 'Genérico',
                'calories': 149,
                'protein': 6.4,
                'carbohydrates': 33.1,
                'fat': 0.5,
                'fiber': 2.1,
                'sugar': 1.0,
                'sodium': 17,
                'serving_size': '100g'
            },
            {
                'name': 'Gengibre',
                'brand': 'Genérico',
                'calories': 80,
                'protein': 1.8,
                'carbohydrates': 17.8,
                'fat': 0.8,
                'fiber': 2.0,
                'sugar': 1.7,
                'sodium': 13,
                'serving_size': '100g'
            },
            {
                'name': 'Couve-Flor',
                'brand': 'Genérico',
                'calories': 25,
                'protein': 1.9,
                'carbohydrates': 5.0,
                'fat': 0.3,
                'fiber': 2.0,
                'sugar': 1.9,
                'sodium': 30,
                'serving_size': '100g'
            },
            {
                'name': 'Repolho',
                'brand': 'Genérico',
                'calories': 25,
                'protein': 1.3,
                'carbohydrates': 5.8,
                'fat': 0.1,
                'fiber': 2.5,
                'sugar': 3.2,
                'sodium': 18,
                'serving_size': '100g'
            },
            {
                'name': 'Couve',
                'brand': 'Genérico',
                'calories': 32,
                'protein': 3.3,
                'carbohydrates': 5.4,
                'fat': 0.6,
                'fiber': 3.6,
                'sugar': 1.3,
                'sodium': 27,
                'serving_size': '100g'
            },
            {
                'name': 'Rúcula',
                'brand': 'Genérico',
                'calories': 25,
                'protein': 2.6,
                'carbohydrates': 3.7,
                'fat': 0.7,
                'fiber': 1.6,
                'sugar': 2.1,
                'sodium': 27,
                'serving_size': '100g'
            },
            {
                'name': 'Agrião',
                'brand': 'Genérico',
                'calories': 11,
                'protein': 2.3,
                'carbohydrates': 1.3,
                'fat': 0.1,
                'fiber': 0.5,
                'sugar': 0.2,
                'sodium': 41,
                'serving_size': '100g'
            },
            {
                'name': 'Salsa',
                'brand': 'Genérico',
                'calories': 36,
                'protein': 3.0,
                'carbohydrates': 6.3,
                'fat': 0.8,
                'fiber': 3.3,
                'sugar': 0.9,
                'sodium': 56,
                'serving_size': '100g'
            },
            {
                'name': 'Coentro',
                'brand': 'Genérico',
                'calories': 23,
                'protein': 2.1,
                'carbohydrates': 3.7,
                'fat': 0.5,
                'fiber': 2.8,
                'sugar': 0.9,
                'sodium': 46,
                'serving_size': '100g'
            },
            {
                'name': 'Manjericão',
                'brand': 'Genérico',
                'calories': 22,
                'protein': 3.2,
                'carbohydrates': 2.6,
                'fat': 0.6,
                'fiber': 1.6,
                'sugar': 0.3,
                'sodium': 4,
                'serving_size': '100g'
            },
            {
                'name': 'Orégano',
                'brand': 'Genérico',
                'calories': 265,
                'protein': 9.0,
                'carbohydrates': 69.0,
                'fat': 4.3,
                'fiber': 42.5,
                'sugar': 4.1,
                'sodium': 25,
                'serving_size': '100g'
            },
            {
                'name': 'Alecrim',
                'brand': 'Genérico',
                'calories': 131,
                'protein': 3.3,
                'carbohydrates': 21.0,
                'fat': 5.9,
                'fiber': 14.1,
                'sugar': 0.0,
                'sodium': 26,
                'serving_size': '100g'
            },
            {
                'name': 'Tomilho',
                'brand': 'Genérico',
                'calories': 101,
                'protein': 5.6,
                'carbohydrates': 24.5,
                'fat': 1.7,
                'fiber': 14.0,
                'sugar': 0.0,
                'sodium': 9,
                'serving_size': '100g'
            },
            
            # Oleaginosas
            {
                'name': 'Amendoim',
                'brand': 'Genérico',
                'calories': 567,
                'protein': 25.8,
                'carbohydrates': 16.1,
                'fat': 49.2,
                'fiber': 8.5,
                'sugar': 4.7,
                'sodium': 18,
                'serving_size': '100g'
            },
            {
                'name': 'Castanha de Caju',
                'brand': 'Genérico',
                'calories': 553,
                'protein': 18.2,
                'carbohydrates': 30.2,
                'fat': 43.9,
                'fiber': 3.3,
                'sugar': 5.9,
                'sodium': 12,
                'serving_size': '100g'
            },
            {
                'name': 'Nozes',
                'brand': 'Genérico',
                'calories': 654,
                'protein': 15.2,
                'carbohydrates': 13.7,
                'fat': 65.2,
                'fiber': 6.7,
                'sugar': 2.6,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Amêndoas',
                'brand': 'Genérico',
                'calories': 579,
                'protein': 21.2,
                'carbohydrates': 21.7,
                'fat': 49.9,
                'fiber': 12.5,
                'sugar': 4.8,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Castanha do Pará',
                'brand': 'Genérico',
                'calories': 656,
                'protein': 14.3,
                'carbohydrates': 12.3,
                'fat': 66.4,
                'fiber': 7.5,
                'sugar': 2.3,
                'sodium': 3,
                'serving_size': '100g'
            },
            {
                'name': 'Pistache',
                'brand': 'Genérico',
                'calories': 560,
                'protein': 20.2,
                'carbohydrates': 27.2,
                'fat': 45.3,
                'fiber': 10.6,
                'sugar': 7.6,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Avelã',
                'brand': 'Genérico',
                'calories': 628,
                'protein': 15.0,
                'carbohydrates': 16.7,
                'fat': 60.8,
                'fiber': 9.7,
                'sugar': 4.3,
                'sodium': 0,
                'serving_size': '100g'
            },
            {
                'name': 'Macadâmia',
                'brand': 'Genérico',
                'calories': 718,
                'protein': 7.9,
                'carbohydrates': 13.8,
                'fat': 75.8,
                'fiber': 8.6,
                'sugar': 4.6,
                'sodium': 5,
                'serving_size': '100g'
            },
            {
                'name': 'Pecã',
                'brand': 'Genérico',
                'calories': 691,
                'protein': 9.2,
                'carbohydrates': 13.9,
                'fat': 72.0,
                'fiber': 9.6,
                'sugar': 4.0,
                'sodium': 0,
                'serving_size': '100g'
            },
            {
                'name': 'Castanha de Caju Torrada',
                'brand': 'Genérico',
                'calories': 553,
                'protein': 18.2,
                'carbohydrates': 30.2,
                'fat': 43.9,
                'fiber': 3.3,
                'sugar': 5.9,
                'sodium': 12,
                'serving_size': '100g'
            },
            {
                'name': 'Amendoim Torrado',
                'brand': 'Genérico',
                'calories': 567,
                'protein': 25.8,
                'carbohydrates': 16.1,
                'fat': 49.2,
                'fiber': 8.5,
                'sugar': 4.7,
                'sodium': 18,
                'serving_size': '100g'
            },
            {
                'name': 'Semente de Chia',
                'brand': 'Genérico',
                'calories': 486,
                'protein': 17.0,
                'carbohydrates': 42.0,
                'fat': 31.0,
                'fiber': 34.0,
                'sugar': 0.0,
                'sodium': 16,
                'serving_size': '100g'
            },
            {
                'name': 'Semente de Linhaça',
                'brand': 'Genérico',
                'calories': 534,
                'protein': 18.3,
                'carbohydrates': 28.9,
                'fat': 42.2,
                'fiber': 27.3,
                'sugar': 1.6,
                'sodium': 30,
                'serving_size': '100g'
            },
            {
                'name': 'Semente de Girassol',
                'brand': 'Genérico',
                'calories': 584,
                'protein': 20.8,
                'carbohydrates': 20.0,
                'fat': 51.5,
                'fiber': 8.6,
                'sugar': 2.6,
                'sodium': 9,
                'serving_size': '100g'
            },
            {
                'name': 'Semente de Abóbora',
                'brand': 'Genérico',
                'calories': 559,
                'protein': 19.0,
                'carbohydrates': 54.0,
                'fat': 19.0,
                'fiber': 18.0,
                'sugar': 1.4,
                'sodium': 18,
                'serving_size': '100g'
            },
            {
                'name': 'Semente de Gergelim',
                'brand': 'Genérico',
                'calories': 573,
                'protein': 17.7,
                'carbohydrates': 23.4,
                'fat': 49.7,
                'fiber': 11.8,
                'sugar': 0.3,
                'sodium': 11,
                'serving_size': '100g'
            },
            
            # Óleos e Gorduras
            {
                'name': 'Azeite de Oliva',
                'brand': 'Genérico',
                'calories': 884,
                'protein': 0.0,
                'carbohydrates': 0.0,
                'fat': 100.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 2,
                'serving_size': '100ml'
            },
            {
                'name': 'Manteiga',
                'brand': 'Genérico',
                'calories': 717,
                'protein': 0.9,
                'carbohydrates': 0.1,
                'fat': 81.1,
                'fiber': 0.0,
                'sugar': 0.1,
                'sodium': 643,
                'serving_size': '100g'
            },
            
            # Leguminosas
            {
                'name': 'Feijão Preto Cozido',
                'brand': 'Genérico',
                'calories': 132,
                'protein': 8.9,
                'carbohydrates': 23.7,
                'fat': 0.5,
                'fiber': 8.7,
                'sugar': 0.3,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Lentilha Cozida',
                'brand': 'Genérico',
                'calories': 116,
                'protein': 9.0,
                'carbohydrates': 20.1,
                'fat': 0.4,
                'fiber': 7.9,
                'sugar': 1.8,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Grão de Bico Cozido',
                'brand': 'Genérico',
                'calories': 164,
                'protein': 8.9,
                'carbohydrates': 27.4,
                'fat': 2.6,
                'fiber': 7.6,
                'sugar': 4.8,
                'sodium': 6,
                'serving_size': '100g'
            },
            {
                'name': 'Feijão Carioca Cozido',
                'brand': 'Genérico',
                'calories': 127,
                'protein': 8.7,
                'carbohydrates': 23.0,
                'fat': 0.5,
                'fiber': 8.5,
                'sugar': 0.3,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Feijão Branco Cozido',
                'brand': 'Genérico',
                'calories': 139,
                'protein': 9.7,
                'carbohydrates': 25.1,
                'fat': 0.5,
                'fiber': 6.3,
                'sugar': 0.3,
                'sodium': 5,
                'serving_size': '100g'
            },
            {
                'name': 'Feijão Vermelho Cozido',
                'brand': 'Genérico',
                'calories': 127,
                'protein': 8.7,
                'carbohydrates': 23.0,
                'fat': 0.5,
                'fiber': 8.5,
                'sugar': 0.3,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Ervilha Cozida',
                'brand': 'Genérico',
                'calories': 84,
                'protein': 5.4,
                'carbohydrates': 14.5,
                'fat': 0.4,
                'fiber': 5.7,
                'sugar': 5.7,
                'sodium': 5,
                'serving_size': '100g'
            },
            {
                'name': 'Soja Cozida',
                'brand': 'Genérico',
                'calories': 173,
                'protein': 16.6,
                'carbohydrates': 9.9,
                'fat': 9.0,
                'fiber': 6.0,
                'sugar': 3.0,
                'sodium': 2,
                'serving_size': '100g'
            },
            {
                'name': 'Fava Cozida',
                'brand': 'Genérico',
                'calories': 110,
                'protein': 7.9,
                'carbohydrates': 19.6,
                'fat': 0.4,
                'fiber': 5.4,
                'sugar': 1.8,
                'sodium': 5,
                'serving_size': '100g'
            },
            {
                'name': 'Tremoço Cozido',
                'brand': 'Genérico',
                'calories': 116,
                'protein': 7.9,
                'carbohydrates': 20.4,
                'fat': 0.4,
                'fiber': 4.8,
                'sugar': 1.8,
                'sodium': 5,
                'serving_size': '100g'
            },
            {
                'name': 'Amendoim Cozido',
                'brand': 'Genérico',
                'calories': 567,
                'protein': 25.8,
                'carbohydrates': 16.1,
                'fat': 49.2,
                'fiber': 8.5,
                'sugar': 4.7,
                'sodium': 18,
                'serving_size': '100g'
            },
            
            # Doces e Sobremesas
            {
                'name': 'Chocolate Amargo 70%',
                'brand': 'Genérico',
                'calories': 598,
                'protein': 7.8,
                'carbohydrates': 45.5,
                'fat': 42.6,
                'fiber': 10.9,
                'sugar': 24.2,
                'sodium': 20,
                'serving_size': '100g'
            },
            {
                'name': 'Mel',
                'brand': 'Genérico',
                'calories': 304,
                'protein': 0.3,
                'carbohydrates': 82.4,
                'fat': 0.0,
                'fiber': 0.2,
                'sugar': 82.1,
                'sodium': 4,
                'serving_size': '100g'
            },
            {
                'name': 'Chocolate ao Leite',
                'brand': 'Genérico',
                'calories': 545,
                'protein': 7.5,
                'carbohydrates': 59.0,
                'fat': 31.0,
                'fiber': 3.4,
                'sugar': 54.0,
                'sodium': 79,
                'serving_size': '100g'
            },
            {
                'name': 'Chocolate Branco',
                'brand': 'Genérico',
                'calories': 539,
                'protein': 5.9,
                'carbohydrates': 59.0,
                'fat': 32.0,
                'fiber': 0.0,
                'sugar': 59.0,
                'sodium': 90,
                'serving_size': '100g'
            },
            {
                'name': 'Sorvete de Baunilha',
                'brand': 'Genérico',
                'calories': 207,
                'protein': 3.5,
                'carbohydrates': 24.0,
                'fat': 11.0,
                'fiber': 0.0,
                'sugar': 21.0,
                'sodium': 80,
                'serving_size': '100g'
            },
            {
                'name': 'Pudim',
                'brand': 'Genérico',
                'calories': 142,
                'protein': 2.5,
                'carbohydrates': 23.0,
                'fat': 4.5,
                'fiber': 0.0,
                'sugar': 20.0,
                'sodium': 50,
                'serving_size': '100g'
            },
            {
                'name': 'Brigadeiro',
                'brand': 'Genérico',
                'calories': 345,
                'protein': 3.0,
                'carbohydrates': 45.0,
                'fat': 18.0,
                'fiber': 1.0,
                'sugar': 40.0,
                'sodium': 30,
                'serving_size': '100g'
            },
            {
                'name': 'Beijinho',
                'brand': 'Genérico',
                'calories': 365,
                'protein': 3.5,
                'carbohydrates': 42.0,
                'fat': 20.0,
                'fiber': 1.5,
                'sugar': 38.0,
                'sodium': 25,
                'serving_size': '100g'
            },
            {
                'name': 'Quindim',
                'brand': 'Genérico',
                'calories': 320,
                'protein': 4.0,
                'carbohydrates': 35.0,
                'fat': 18.0,
                'fiber': 0.5,
                'sugar': 32.0,
                'sodium': 40,
                'serving_size': '100g'
            },
            {
                'name': 'Paçoca',
                'brand': 'Genérico',
                'calories': 485,
                'protein': 12.0,
                'carbohydrates': 45.0,
                'fat': 28.0,
                'fiber': 4.0,
                'sugar': 35.0,
                'sodium': 15,
                'serving_size': '100g'
            },
            {
                'name': 'Pé de Moleque',
                'brand': 'Genérico',
                'calories': 420,
                'protein': 8.0,
                'carbohydrates': 50.0,
                'fat': 22.0,
                'fiber': 3.0,
                'sugar': 40.0,
                'sodium': 20,
                'serving_size': '100g'
            },
            {
                'name': 'Cocada',
                'brand': 'Genérico',
                'calories': 380,
                'protein': 3.0,
                'carbohydrates': 55.0,
                'fat': 18.0,
                'fiber': 2.0,
                'sugar': 50.0,
                'sodium': 25,
                'serving_size': '100g'
            },
            {
                'name': 'Rapadura',
                'brand': 'Genérico',
                'calories': 380,
                'protein': 0.0,
                'carbohydrates': 95.0,
                'fat': 0.0,
                'fiber': 0.0,
                'sugar': 95.0,
                'sodium': 5,
                'serving_size': '100g'
            },
            {
                'name': 'Açúcar Refinado',
                'brand': 'Genérico',
                'calories': 387,
                'protein': 0.0,
                'carbohydrates': 100.0,
                'fat': 0.0,
                'fiber': 0.0,
                'sugar': 100.0,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Açúcar Mascavo',
                'brand': 'Genérico',
                'calories': 380,
                'protein': 0.0,
                'carbohydrates': 98.0,
                'fat': 0.0,
                'fiber': 0.0,
                'sugar': 98.0,
                'sodium': 20,
                'serving_size': '100g'
            },
            {
                'name': 'Açúcar Demerara',
                'brand': 'Genérico',
                'calories': 387,
                'protein': 0.0,
                'carbohydrates': 100.0,
                'fat': 0.0,
                'fiber': 0.0,
                'sugar': 100.0,
                'sodium': 1,
                'serving_size': '100g'
            },
            {
                'name': 'Stevia',
                'brand': 'Genérico',
                'calories': 0,
                'protein': 0.0,
                'carbohydrates': 0.0,
                'fat': 0.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 0,
                'serving_size': '100g'
            },
            {
                'name': 'Xilitol',
                'brand': 'Genérico',
                'calories': 240,
                'protein': 0.0,
                'carbohydrates': 100.0,
                'fat': 0.0,
                'fiber': 0.0,
                'sugar': 0.0,
                'sodium': 0,
                'serving_size': '100g'
            }
        ]
        
        # Filtrar alimentos baseado na query
        query_lower = query.lower()
        filtered_foods = []
        
        for food in sample_foods:
            if query_lower in food['name'].lower() or query_lower in food['brand'].lower():
                filtered_foods.append(food)
        
        # Se não encontrar nada, retornar alguns alimentos populares
        if not filtered_foods:
            filtered_foods = sample_foods[:8]
        
        return filtered_foods
    
    def search_usda(self, query: str) -> List[Dict[str, Any]]:
        """
        Busca alimentos na API do USDA FoodData Central
        Em produção, você precisaria de uma chave de API válida
        """
        # Simulação da API do USDA
        return self.search_fatsecret(query)  # Usando os mesmos dados por simplicidade
    
    def search_food(self, query: str, api_source: str = 'fatsecret') -> List[Dict[str, Any]]:
        """
        Busca alimentos em diferentes APIs
        """
        if api_source == 'fatsecret':
            return self.search_fatsecret(query)
        elif api_source == 'usda':
            return self.search_usda(query)
        else:
            return self.search_fatsecret(query)  # Padrão 